<a href="https://colab.research.google.com/github/arathichandran055-svg/python-project-2/blob/main/python_project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import pandas as pd

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:
file_path ="/content/drive/MyDrive/Colab Notebooks/Titanic-Dataset (1).csv"

In [11]:
data=pd.read_csv(file_path)

In [12]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [14]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [15]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Titanic-Dataset (1).csv")
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [16]:
type(data)
age_series = data['Age']
fare_series = data['Fare']
survived_series = data['Survived']

print(type(age_series))

<class 'pandas.core.series.Series'>

In [17]:
data.head()
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [27]:
data["Age"] = data["Age"].fillna(data["Age"].mean())
data["Embarked"] = data["Embarked"].fillna(data["Embarked"].mode()[0])

In [28]:
data.iloc[0]
data.iloc[0][['Age', 'Fare']]
data.iloc[0:6, 2:6]

    Pclass                                               Name  Gender   Age
1        1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
3        1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
6        1                            McCarthy, Mr. Timothy J    male  54.0
10       3                    Sandstrom, Miss. Marguerite Rut  female   4.0
11       1                           Bonnell, Miss. Elizabeth  female  58.0
21       2                              Beesley, Mr. Lawrence    male  34.0

In [21]:
data.rename(columns={'Sex': 'Gender'}, inplace=True)
pivot_table = data.pivot_table(values='Survived',
                             index='Gender',
                             aggfunc='mean')
melted = pd.melt(data, id_vars=['PassengerId'],
                 value_vars=['Age', 'Fare'])

In [23]:

data[data['Age'] > 30]
data[data['Fare'] > 50]
data[(data['Gender'] == 'female') & (data['Survived'] == 1)]
data.sort_values(by='Fare', ascending=False)
data.sort_values(by='Age')
data.sort_values(by='Survived', ascending=False)

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.000000,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.000000,0,0,113783,26.5500,C103,S
55,56,1,1,"Woolner, Mr. Hugh",male,29.699118,0,0,19947,35.5000,C52,S
...,...,...,...,...,...,...,...,...,...,...,...,...
776,777,0,3,"Tobin, Mr. Roger",male,29.699118,0,0,383121,7.7500,F38,Q
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.000000,1,1,WE/P 5735,71.0000,B22,S
815,816,0,1,"Fry, Mr. Richard",male,29.699118,0,0,112058,0.0000,B102,S
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.000000,0,0,PC 17590,50.4958,A24,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.000000,0,0,695,5.0000,B51 B53 B55,S

In [25]:
data.groupby('Gender')['Survived'].mean()
data.groupby('Pclass')['Age'].mean()
data.groupby('Embarked')['Survived'].sum()

Embarked
C    52
Q     2
S    82
Name: Survived, dtype: int64

In [24]:
class_info = pd.DataFrame({
    'Pclass': [1, 2, 3],
    'Category': ['Upper', 'Middle', 'Lower']
})
merged_df = pd.merge(data, class_info, on='Pclass')
data.join(class_info.set_index('Pclass'), on='Pclass')
concat_data = pd.concat([data.head(), data.tail()])

In [26]:
data.groupby('Survived')['Age'].mean()
data['Fare'].max()
data['Fare'].min()
survival_rate = data['Survived'].mean() * 100
print("Survival Percentage:", survival_rate)

Survival Percentage: 66.66666666666666